import React, { FC, useContext, useEffect, useRef, useState } from 'react';
import { SystemsDiagram } from '../components/SystemDiagram/SystemDiagram';
import { FullScreen } from './components/FullScreen/FullScreen';
import './styles.css'

export const SystemsMapPage: FC = () => {
   const diagramContainerRef = useRef<HTMLDivElement>(null);

  const data:any = {
    nodes:[
      {
         "id":27,
         "category":"system",
         "description":"This system its in charge of managing the tool that allows you to design and diagnose systems health.",
         "group":"root",
         "key":"sys-27",
         "isGroup":true,
         "hasNodes":true,
         "technology":"",
         "text":"Meli System",
         "expanded":true
      },
      {
         "id":0,
         "category":"group-services",
         "description":"",
         "group":"sys-27",
         "key":"grp-srv-sys-27",
         "isGroup":true,
         "hasNodes":true,
         "technology":"",
         "text":"",
         "expanded":false
      },
      {
         "id":148,
         "category":"microservice",
         "description":"some-fancy-description",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-148",
         "isGroup":true,
         "hasNodes":true,
         "technology":"[Container: PHP]",
         "text":"meli-system-feature-flag",
         "expanded":false
      },
      {
         "id":215,
         "category":"microservice",
         "description":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-215",
         "isGroup":true,
         "hasNodes":true,
         "technology":"[Container: Kotlin]",
         "text":"meli-system-session-handler",
         "expanded":false
      },
      {
         "id":239,
         "category":"microservice",
         "description":"some-fancy-description",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-239",
         "isGroup":true,
         "hasNodes":true,
         "technology":"[Container: Python]",
         "text":"meli-system-gateway",
         "expanded":false
      },
      {
         "id":261,
         "category":"microservice",
         "description":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-261",
         "isGroup":true,
         "hasNodes":true,
         "technology":"[Container: Java]",
         "text":"meli-system-events-handler",
         "expanded":false
      },
      {
         "id":4,
         "category":"microservice",
         "description":"some-fancy-description",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-4",
         "isGroup":true,
         "hasNodes":true,
         "technology":"[Container: PHP]",
         "text":"meli-system-traffic-decorator",
         "expanded":false
      },
      {
         "id":57,
         "category":"microservice",
         "description":"some-fancy-description",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-57",
         "isGroup":true,
         "hasNodes":true,
         "technology":"[Container: Go]",
         "text":"system-manager",
         "expanded":false
      },
      {
         "id":2943,
         "category":"scope",
         "description":"1.2.0",
         "group":"sys-27-mcr-4",
         "key":"scp-2943",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"prod-job",
         "expanded":false
      },
      {
         "id":2996,
         "category":"scope",
         "description":"1.0.2-rc-5",
         "group":"sys-27-mcr-148",
         "key":"scp-2996",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"stress",
         "expanded":false
      },
      {
         "id":3047,
         "category":"scope",
         "description":"1.15.0-hotfix-9",
         "group":"sys-27-mcr-57",
         "key":"scp-3047",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"stress",
         "expanded":false
      },
      {
         "id":3098,
         "category":"scope",
         "description":"1.0.0-rc-12",
         "group":"sys-27-mcr-215",
         "key":"scp-3098",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"stress",
         "expanded":false
      },
      {
         "id":3147,
         "category":"scope",
         "description":"1.0.0",
         "group":"sys-27-mcr-215",
         "key":"scp-3147",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"production",
         "expanded":false
      },
      {
         "id":3193,
         "category":"scope",
         "description":"1.0.2",
         "group":"sys-27-mcr-148",
         "key":"scp-3193",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"production",
         "expanded":false
      },
      {
         "id":3243,
         "category":"scope",
         "description":"1.15.0",
         "group":"sys-27-mcr-57",
         "key":"scp-3243",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"production",
         "expanded":false
      },
      {
         "id":3292,
         "category":"scope",
         "description":"1.19.1",
         "group":"sys-27-mcr-239",
         "key":"scp-3292",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"production",
         "expanded":false
      },
      {
         "id":3338,
         "category":"scope",
         "description":"1.19.1",
         "group":"sys-27-mcr-239",
         "key":"scp-3338",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"stress",
         "expanded":false
      },
      {
         "id":3386,
         "category":"scope",
         "description":"1.3.7",
         "group":"sys-27-mcr-261",
         "key":"scp-3386",
         "isGroup":false,
         "hasNodes":false,
         "technology":"[Container: undefined]",
         "text":"production",
         "expanded":false
      },
      {
         "id":2249,
         "category":"MySQL",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-148-stg-2249",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"MySQL",
         "expanded":false
      },
      {
         "id":2546,
         "category":"Object Storage",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-215-stg-2546",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"Object Storage",
         "expanded":false
      },
      {
         "id":2547,
         "category":"Cache",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-215-stg-2547",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"Cache",
         "expanded":false
      },
      {
         "id":387,
         "category":"DS",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-215-stg-387",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"DS",
         "expanded":false
      },
      {
         "id":2544,
         "category":"Object Storage",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-239-stg-2544",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"Object Storage",
         "expanded":false
      },
      {
         "id":2545,
         "category":"Cache",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-239-stg-2545",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"Cache",
         "expanded":false
      },
      {
         "id":2542,
         "category":"Object Storage",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-57-stg-2542",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"Object Storage",
         "expanded":false
      },
      {
         "id":2543,
         "category":"Cache",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-57-stg-2543",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"Cache",
         "expanded":false
      },
      {
         "id":508,
         "category":"MySQL",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-57-stg-508",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"MySQL",
         "expanded":false
      },
      {
         "id":514,
         "category":"KVS",
         "description":"",
         "group":"grp-srv-sys-27",
         "key":"sys-27-mcr-57-stg-514",
         "isGroup":false,
         "hasNodes":false,
         "technology":"",
         "text":"KVS",
         "expanded":false
      }
   ],
   links:[
      {
         "key":"scp-3292-scp-3243-cst",
         "from":"scp-3292",
         "to":"scp-3243"
      },
      {
         "key":"sys-27-mcr-57-sys-27-mcr-57-stg-514-cst",
         "from":"sys-27-mcr-57",
         "to":"sys-27-mcr-57-stg-514"
      },
      {
         "key":"scp-3147-scp-3243-cst",
         "from":"scp-3147",
         "to":"scp-3243"
      },
      {
         "key":"sys-27-mcr-148-sys-27-mcr-148-stg-2249-cst",
         "from":"sys-27-mcr-148",
         "to":"sys-27-mcr-148-stg-2249"
      },
      {
         "key":"sys-27-mcr-57-sys-27-mcr-57-stg-508-cst",
         "from":"sys-27-mcr-57",
         "to":"sys-27-mcr-57-stg-508"
      },
      {
         "key":"scp-3338-scp-3098-cst",
         "from":"scp-3338",
         "to":"scp-3098"
      },
      {
         "key":"sys-27-mcr-215-sys-27-mcr-215-stg-2546-cst",
         "from":"sys-27-mcr-215",
         "to":"sys-27-mcr-215-stg-2546"
      },
      {
         "key":"scp-3338-scp-3047-cst",
         "from":"scp-3338",
         "to":"scp-3047"
      },
      {
         "key":"scp-2943-scp-3292-cst",
         "from":"scp-2943",
         "to":"scp-3292"
      },
      {
         "key":"sys-27-mcr-239-sys-27-mcr-239-stg-2544-cst",
         "from":"sys-27-mcr-239",
         "to":"sys-27-mcr-239-stg-2544"
      },
      {
         "key":"scp-3098-scp-3047-cst",
         "from":"scp-3098",
         "to":"scp-3047"
      },
      {
         "key":"scp-3292-scp-3193-cst",
         "from":"scp-3292",
         "to":"scp-3193"
      },
      {
         "key":"sys-27-mcr-57-sys-27-mcr-57-stg-2542-cst",
         "from":"sys-27-mcr-57",
         "to":"sys-27-mcr-57-stg-2542"
      },
      {
         "key":"sys-27-mcr-215-sys-27-mcr-215-stg-2547-cst",
         "from":"sys-27-mcr-215",
         "to":"sys-27-mcr-215-stg-2547"
      },
      {
         "key":"scp-3338-scp-2996-cst",
         "from":"scp-3338",
         "to":"scp-2996"
      },
      {
         "key":"sys-27-mcr-57-sys-27-mcr-57-stg-2543-cst",
         "from":"sys-27-mcr-57",
         "to":"sys-27-mcr-57-stg-2543"
      },
      {
         "key":"scp-3292-scp-3147-cst",
         "from":"scp-3292",
         "to":"scp-3147"
      },
      {
         "key":"scp-3386-scp-3243-cst",
         "from":"scp-3386",
         "to":"scp-3243"
      },
      {
         "key":"sys-27-mcr-239-sys-27-mcr-239-stg-2545-cst",
         "from":"sys-27-mcr-239",
         "to":"sys-27-mcr-239-stg-2545"
      },
      {
         "key":"sys-27-mcr-215-sys-27-mcr-215-stg-387-cst",
         "from":"sys-27-mcr-215",
         "to":"sys-27-mcr-215-stg-387"
      }
   ]
  };
  
  return (
    <>
      <div className='containerDiagram' ref={diagramContainerRef}>
      <FullScreen elementRef={diagramContainerRef} />
        <SystemsDiagram
          model={data}
        />
      </div>
      
    </>
  );
};
